import { StyleSheet } from "react-native";

// 이 화면 전용 라이트 팔레트 (공유 colors.ts 다크 토큰과 분리)
export const light = {
  bg: "#13142C",
  surface: "#191B31",
  surfaceAlt: "#22253F",
  input: "#0E0F21",
  textPrimary: "#F7F7F7",
  textSecondary: "#C7C8D6",
  textHint: "#8B8EA8",
  border: "#22253F",
  overlay: "rgba(14,15,33,0.72)",
  accent: "#F5F3C2",
  accentText: "#0E0F21",
  pink: "#EC56A7",
  green: "#75CF67",
  purple: "#9773FF",
} as const;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    position: "relative",
    backgroundColor: light.bg,
  },

  // 헤더
  header: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  headerCircleButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: light.surface,
  },
  anlasChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    height: 32,
    borderRadius: 16,
    backgroundColor: light.surface,
  },
  anlasChipText: {
    fontSize: 14,
    fontWeight: "600",
    color: light.textPrimary,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },

  // 중단: 이미지 영역
  imageSlot: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
    overflow: "hidden",
  },
  imageCard: {
    borderRadius: 18,
    backgroundColor: light.surfaceAlt,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  generatedImage: {
    width: "100%",
    height: "100%",
    borderRadius: 18,
    overflow: "hidden",
  },
  imageOverlayRow: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    gap: 8,
  },
  imageOverlayButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: light.overlay,
  },

  // 하단: 옵션 + 생성 버튼
  bottomArea: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 8,
    gap: 12,
  },
  generateControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
  },
  generateButtonWrap: {
    flex: 1,
  },
  generateButton: {
    width: "100%",
    height: 54,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: light.accent,
  },
  generateButtonText: {
    color: light.accentText,
    fontSize: 16,
    fontWeight: "700",
  },
  batchCountButton: {
    height: 54,
    minWidth: 82,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 14,
    backgroundColor: light.surface,
  },
  batchCountButtonText: {
    color: light.textSecondary,
    fontSize: 16,
    fontWeight: "700",
  },
  promptCard: {
    marginHorizontal: 16,
    borderRadius: 22,
    backgroundColor: light.input,
    borderWidth: 1,
    borderColor: light.border,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  // 측정 자유(고정 height 없음) → onContentSizeChange 가 콘텐츠 실제 높이 보고.
  // absolute 라 wrapper(애니메이션 height)에 영향 안 줌.
  promptInput: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    minHeight: 44,
    maxHeight: 140,
    paddingRight: 36,
    fontSize: 16,
    color: light.textPrimary,
  },
  expandButton: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  promptActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  promptActionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  promptModePill: {
    flexDirection: "row",
    alignItems: "center",
    height: 34,
    borderRadius: 999,
    backgroundColor: light.surface,
    padding: 3,
    overflow: "hidden",
  },
  promptModeSegment: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    zIndex: 1,
  },
  promptModeThumb: {
    position: "absolute",
    top: 3,
    bottom: 3,
    borderRadius: 999,
    backgroundColor: light.surfaceAlt,
  },
  characterButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    height: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: light.border,
    backgroundColor: light.input,
  },
  characterButtonText: {
    fontSize: 13,
    fontWeight: "500",
    color: light.textSecondary,
  },
  promptModeText: {
    fontSize: 13,
    fontWeight: "500",
    color: light.textHint,
  },
  promptModeTextActive: {
    color: light.textPrimary,
  },
  plusButton: {
    width: 34,
    height: 34,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: light.border,
    backgroundColor: light.input,
  },
  submitButton: {
    width: 34,
    height: 34,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: light.accent,
  },
  submitButtonProgressText: {
    color: light.accentText,
    fontSize: 12,
    fontWeight: "700",
  },

  // 하단: 옵션 패널
  optionPanel: {
    marginHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: light.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    overflow: "hidden",
    backgroundColor: light.input,
  },
  optionPanelHeader: {
    minHeight: 40,
    justifyContent: "center",
  },
  optionPanelSummaryRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  optionPanelSummary: {
    flex: 1,
    color: light.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  optionPanelChevron: {
    marginTop: 1,
  },
  optionPanelGroups: {
    paddingTop: 10,
    gap: 9,
  },
  optionGroupRow: {
    gap: 6,
  },
  optionGroupLabel: {
    color: light.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  optionGroupScroll: {
    flex: 1,
  },
  optionGroupChips: {
    flexDirection: "row",
    gap: 6,
    paddingRight: 2,
  },
  compactOptionChip: {
    minHeight: 28,
    maxWidth: 136,
    borderWidth: 1,
    borderColor: "transparent",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    justifyContent: "center",
    backgroundColor: light.input,
  },
  compactOptionChipActive: {
    borderColor: light.accent,
    backgroundColor: "rgba(245,243,194,0.14)",
  },
  compactOptionChipText: {
    color: light.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  compactOptionChipTextActive: {
    color: light.accent,
  },
  optionChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    height: 36,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: light.input,
  },
  optionChipActive: {
    backgroundColor: light.accent,
  },
  optionChipText: {
    fontSize: 14,
    fontWeight: "500",
    color: light.textSecondary,
  },
  optionChipUnit: {
    fontSize: 13,
    fontWeight: "400",
    color: light.textHint,
  },
  optionChipTextActive: {
    color: light.accentText,
  },

  // 모델 선택 바텀시트 (라이트)
  sheetContainer: {
    zIndex: 100,
    elevation: 100,
  },
  sheetBackground: {
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    backgroundColor: light.bg,
  },
  sheetHandle: {
    width: 56,
    height: 5,
    backgroundColor: light.border,
  },
  sheetScrollContent: {
    width: "100%",
    alignItems: "stretch",
    paddingHorizontal: 20,
    paddingBottom: 24,
    gap: 2,
  },
  sheetRouteContent: {
    width: "100%",
    alignSelf: "stretch",
  },
  sheetTitle: {
    paddingHorizontal: 4,
    paddingTop: 8,
    paddingBottom: 12,
    color: light.textPrimary,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    includeFontPadding: false,
  },
  sheetModelItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 50,
    paddingHorizontal: 12,
    marginHorizontal: -8,
    borderRadius: 14,
  },
  sheetModelItemLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  sheetModelItemLabel: {
    color: light.textSecondary,
    fontSize: 17,
    fontWeight: "600",
  },
  sheetModelItemLabelActive: {
    color: light.accent,
  },
  sheetModelItemBadge: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: light.surfaceAlt,
  },
  sheetModelItemBadgeText: {
    color: light.textHint,
    fontSize: 11,
    fontWeight: "700",
  },
  sheetDivider: {
    height: 1,
    backgroundColor: light.border,
    marginVertical: 12,
  },

  // 옵션 시트 — 상세 백 헤더 / 루트 메뉴
  sheetBackHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 4,
    marginBottom: 10,
    minHeight: 44,
  },
  sheetBackButton: {
    width: 36,
    height: 36,
    marginLeft: -8,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetBackTitle: {
    flex: 1,
    color: light.textPrimary,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    includeFontPadding: false,
    marginLeft: 0,
  },
  sheetMenuGroupLabel: {
    color: light.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 4,
    paddingTop: 14,
    paddingBottom: 4,
  },
  sheetMenuRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 52,
    paddingHorizontal: 12,
    marginHorizontal: -8,
    borderRadius: 14,
    gap: 12,
  },
  sheetMenuTileRow: {
    flexDirection: "row",
    width: "100%",
    alignSelf: "stretch",
    gap: 8,
    marginBottom: 4,
  },
  sheetMenuTileCell: {
    flex: 1,
  },
  sheetMenuTile: {
    width: "100%",
    minHeight: 64,
    justifyContent: "center",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: light.surface,
  },
  sheetMenuTileLabel: {
    color: light.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  sheetMenuTileValue: {
    color: light.textPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  sheetMenuLabel: {
    color: light.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  sheetMenuLabelDisabled: {
    color: light.textHint,
  },
  sheetMenuValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 1,
  },
  sheetMenuValue: {
    color: light.textSecondary,
    fontSize: 14,
    fontWeight: "600",
    flexShrink: 1,
  },
  sheetMenuValueActive: {
    color: light.accent,
  },

  // Steps 바텀시트
  stepsValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 28,
  },
  stepsButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: light.surface,
  },
  stepsButtonDisabled: {
    opacity: 0.4,
  },
  stepsValueCenter: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 6,
  },
  stepsValueInput: {
    minWidth: 56,
    height: 52,
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 44,
    lineHeight: 52,
    fontWeight: "bold",
    color: light.textPrimary,
    padding: 0,
    includeFontPadding: false,
  },
  stepsValueUnit: {
    fontSize: 16,
    fontWeight: "500",
    color: light.textHint,
  },
  stepsNativeSlider: {
    width: "100%",
    height: 40,
  },
  stepsRangeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    paddingHorizontal: 4,
  },
  stepsRangeLabel: {
    fontSize: 13,
    fontWeight: "500",
    color: light.textHint,
  },

  // Seed 바텀시트
  seedSheetRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
    marginBottom: 14,
  },
  seedSheetInput: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 18,
    fontWeight: "600",
    color: light.textPrimary,
    backgroundColor: light.input,
    padding: 0,
    includeFontPadding: false,
  },
  seedSheetInputLocked: {
    color: light.textHint,
  },
  seedSheetButton: {
    width: 52,
    height: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: light.surface,
  },
  seedSheetButtonActive: {
    backgroundColor: "rgba(245,243,194,0.14)",
  },
  seedSheetHint: {
    paddingHorizontal: 4,
    fontSize: 13,
    fontWeight: "500",
    color: light.textHint,
  },

  // Resolution 바텀시트
  resolutionInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
    marginBottom: 16,
  },
  resolutionInputBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: 52,
    borderRadius: 14,
    paddingHorizontal: 14,
    gap: 8,
    backgroundColor: light.input,
  },
  resolutionInputLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: light.textHint,
  },
  resolutionInput: {
    flex: 1,
    height: 52,
    fontSize: 18,
    fontWeight: "600",
    color: light.textPrimary,
    padding: 0,
    includeFontPadding: false,
  },
  resolutionSwapButton: {
    width: 44,
    height: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: light.surface,
  },
  resolutionGroupLabel: {
    paddingHorizontal: 4,
    paddingTop: 14,
    paddingBottom: 4,
    fontSize: 13,
    fontWeight: "700",
    color: light.textHint,
    textTransform: "uppercase",
  },
});
