import { tokens } from "../../styles/tokens";

export const playerLayoutTokens = {
  color: {
    app: tokens.color.app,
    sheet: "#000000",
    card: tokens.color.card,
    cardAlt: tokens.color.cardAlt,
    panel: tokens.color.sunken,
    raised: tokens.color.raised,
    accent: tokens.color.accent,
    onAccent: tokens.color.onAccent,
    textPrimary: tokens.color.textPrimary,
    textSecondary: tokens.color.textSecondary,
    textTertiary: tokens.color.textTertiary,
    textMuted: tokens.color.textMuted,
    textNegative: tokens.color.negative,
    borderSubtle: tokens.color.borderSubtle,
    borderNegative: tokens.color.borderNegative,
    controlTrackOff: "#232326",
    segmentInactive: "#232326",
    badge1: tokens.color.badge1,
    badge2: tokens.color.badge2,
    badge3: tokens.color.badge3,
    badge4: tokens.color.badge4,
    placeholderStripe: tokens.color.placeholderStripe,
    panelHandle: "rgba(255,255,255,0.22)",
  },
  layout: {
    referenceWidth: 402,
    contentTop: 60,
    contentBottom: 150,
    mainInset: 14,
    panelInset: 16,
    miniHeight: 68,
    miniBottomGap: 8,
    tabBarHeight: 62,
    tabBarBottomPadding: 0,
    panelTop: 110,
    fullImageWidth: 364,
    fullImageHeight: 568,
    miniImageSize: 44,
    miniImageLeft: 12,
    miniImageTop: 16,
    fullImageLeft: 14,
    fullImageTop: 112,
    dockImageTop: 52,
    dockTop: 46,
    dockHeight: 56,
    sheetHeaderCollapsed: 68,
    sheetHeaderExpanded: 130,
    fullHeaderTopCollapsed: 20,
    fullHeaderTopExpanded: 54,
    actionTopExpanded: 692,
    actionTopCollapsed: 782,
    actionTravel: 90,
    tabBarTravel: 96,
    fullBottomPadding: 20,
    imageActionHeight: 40,
    imageToActionGap: 10,
    imageActionToControlsGap: 16,
    fullGenerateHeight: 54,
  },
  radius: {
    sheet: 26,
    panel: 22,
    panelCard: 24,
    hero: 20,
    account: 18,
    tile: 14,
    segment: 12,
    thumbnail: 10,
    pill: 999,
  },
  motion: {
    sheetDuration: 380,
    fadeDuration: 240,
    switchDuration: 180,
    easing: [0.32, 0.72, 0, 1] as const,
    openThreshold: -40,
    closeThreshold: 140,
    panelCloseThreshold: 150,
    closedRubberBand: 60,
    panelClosedOvershoot: 20,
    scrimMaxOpacity: 0.55,
    tabBarFadeMultiplier: 1.6,
    miniFadeMultiplier: 2.2,
    contentFadeStart: 0.45,
    contentFadeRange: 0.55,
    panActivationOffset: 4,
    panHorizontalFailOffset: 12,
  },
} as const;
