import { tokens } from "../../styles/tokens";

export const playerLayoutTokens = {
  color: {
    app: tokens.color.app,
    sheet: "#000000",
    card: tokens.color.card,
    cardAlt: tokens.color.cardAlt,
    panel: tokens.color.sunken,
    raised: tokens.color.raised,
    accent: tokens.color.accent,
    onAccent: tokens.color.onAccent,
    textPrimary: tokens.color.textPrimary,
    textSecondary: tokens.color.textSecondary,
    textTertiary: tokens.color.textTertiary,
    textMuted: tokens.color.textMuted,
    borderSubtle: tokens.color.borderSubtle,
    placeholderStripe: tokens.color.placeholderStripe,
    panelHandle: "rgba(255,255,255,0.22)",
  },
  layout: {
    referenceWidth: 402,
    contentTop: 60,
    contentBottom: 176,
    mainInset: 14,
    panelInset: 16,
    miniHeight: 76,
    tabBarHeight: 88,
    tabBarBottomPadding: 26,
    panelTop: 126,
    fullImageWidth: 364,
    fullImageHeight: 460,
    miniImageSize: 44,
    miniImageLeft: 12,
    miniImageTop: 16,
    fullImageLeft: 14,
    fullImageTop: 134,
    dockImageTop: 64,
    dockTop: 54,
    dockHeight: 64,
    sheetHeaderCollapsed: 76,
    sheetHeaderExpanded: 130,
    fullHeaderTopCollapsed: 20,
    fullHeaderTopExpanded: 74,
    actionTopExpanded: 608,
    actionTopCollapsed: 698,
    tabBarTravel: 96,
    homeBarHeight: 26,
    fullBottomPadding: 36,
    imageActionHeight: 34,
    entryChipHeight: 36,
    fullGenerateHeight: 54,
  },
  radius: {
    sheet: 26,
    panel: 22,
    panelCard: 28,
    hero: 20,
    account: 18,
    tile: 14,
    segment: 12,
    thumbnail: 10,
    pill: 999,
  },
  motion: {
    sheetDuration: 380,
    fadeDuration: 240,
    switchDuration: 180,
    easing: [0.32, 0.72, 0, 1] as const,
    openThreshold: -40,
    closeThreshold: 140,
    panelCloseThreshold: 150,
    closedRubberBand: 60,
    panelClosedOvershoot: 20,
    scrimMaxOpacity: 0.55,
    tabBarFadeMultiplier: 1.6,
    miniFadeMultiplier: 2.2,
    contentFadeStart: 0.45,
    contentFadeRange: 0.55,
    panActivationOffset: 4,
    panHorizontalFailOffset: 12,
  },
} as const;
