import { Platform, StyleSheet } from "react-native";

import { colors } from "../../styles/colors";

export const SEEK_THUMB_WIDTH = 8;
export const SEEK_THUMB_HEIGHT = 20;
export const SEEK_THUMB_TOUCH_SIZE = 38;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? 28 : 0,
    backgroundColor: colors.appBackground,
  },
  tabView: {
    flex: 1,
  },
  tabBar: {
    marginHorizontal: 16,
    backgroundColor: "transparent",
    elevation: 0,
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 0,
  },
  tabIndicator: {
    height: 3,
    backgroundColor: colors.colorBorderInfo,
  },
  tabContent: {
    padding: 16,
    paddingBottom: 24,
  },
  loadingOptions: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  footer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    backgroundColor: colors.appBackground,
  },
  generateButton: {
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: colors.colorBackgroundInverse,
  },
  disabledButton: {
    opacity: 0.62,
  },
  generateText: {
    color: colors.colorTextInverse,
    fontSize: 18,
    fontWeight: "800",
  },
  inputGroup: {
    marginBottom: 22,
  },
  inputLabel: {
    marginBottom: 10,
    color: colors.colorTextPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  textAreaWrap: {
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    padding: 14,
    backgroundColor: colors.colorBackgroundTertiary,
  },
  textArea: {
    flex: 1,
    minHeight: 70,
    color: colors.colorTextPrimary,
    fontSize: 15,
    lineHeight: 23,
  },
  countText: {
    alignSelf: "flex-end",
    marginTop: 8,
    color: colors.colorTextTertiary,
    fontSize: 12,
  },
  optionLabel: {
    color: colors.colorTextPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  optionValue: {
    maxWidth: "58%",
    color: colors.colorTextTertiary,
    fontSize: 14,
    textAlign: "right",
  },
  optionBlock: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    padding: 16,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  optionBody: {
    marginTop: 12,
  },
  resolutionInputRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  resolutionInput: {
    flex: 1,
    height: 38,
    borderWidth: 1,
    borderColor: colors.colorBorderSecondary,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 0,
    backgroundColor: colors.colorBackgroundTertiary,
    color: colors.colorTextPrimary,
    fontWeight: "800",
    includeFontPadding: false,
    textAlign: "center",
    textAlignVertical: "center",
  },
  resolutionSwapButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: colors.colorBackgroundTertiary,
  },
  resolutionSwapText: {
    color: colors.colorTextPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  section: {
    marginBottom: 10,
  },
  sectionHeader: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    paddingLeft: 3,
    color: colors.colorTextPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  sectionChevron: {
    width: 28,
    color: colors.colorTextSecondary,
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
    marginRight: -3,
  },
  sectionBody: {
    overflow: "hidden",
  },
  sectionContent: {
    paddingTop: 10,
  },
  selectOption: {
    marginBottom: 10,
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  selectValueWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    justifyContent: "flex-end",
    marginLeft: 16,
  },
  selectChevron: {
    color: colors.colorTextTertiary,
    fontSize: 22,
    fontWeight: "800",
  },
  segmentRow: {
    flexDirection: "row",
    gap: 10,
  },
  segmentButton: {
    flex: 1,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.colorBorderSecondary,
    borderRadius: 10,
    backgroundColor: colors.colorBackgroundTertiary,
  },
  segmentButtonActive: {
    borderColor: colors.colorBorderInfo,
    backgroundColor: colors.colorBackgroundInfo,
  },
  segmentText: {
    color: colors.colorTextTertiary,
    fontWeight: "700",
  },
  segmentTextActive: {
    color: colors.colorTextPrimary,
  },
  stepperRow: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 2,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  stepperTopRow: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  stepper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  stepperLabel: {
    flex: 1,
    marginRight: 12,
  },
  stepButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: colors.colorBackgroundTertiary,
  },
  stepButtonText: {
    color: colors.colorTextPrimary,
    fontSize: 20,
    fontWeight: "800",
  },
  stepValue: {
    width: 48,
    color: colors.colorTextPrimary,
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
  seekContainer: {
    marginTop: 0,
  },
  seekTrackWrap: {
    height: SEEK_THUMB_TOUCH_SIZE,
    justifyContent: "center",
  },
  seekTrack: {
    height: 12,
    overflow: "hidden",
    borderRadius: 6,
    backgroundColor: colors.colorBorderTertiary,
  },
  seekThumbTouch: {
    position: "absolute",
    top: 0,
    left: 0,
    width: SEEK_THUMB_TOUCH_SIZE,
    height: SEEK_THUMB_TOUCH_SIZE,
    alignItems: "center",
    justifyContent: "center",
  },
  seekThumb: {
    width: SEEK_THUMB_WIDTH,
    height: SEEK_THUMB_HEIGHT,
    borderRadius: 4,
    backgroundColor: colors.colorBackgroundInverse,
  },
  seedOptionRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  seedRow: {
    width: 136,
    flexDirection: "row",
    gap: 10,
    marginLeft: 16,
  },
  seedInput: {
    flex: 1,
    height: 38,
    borderWidth: 1,
    borderColor: colors.colorBorderSecondary,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 0,
    backgroundColor: colors.colorBackgroundTertiary,
    color: colors.colorTextPrimary,
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  sheetContainer: {
    marginHorizontal: 14,
    zIndex: 20,
    elevation: 20,
  },
  sheetBackground: {
    borderRadius: 28,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  sheetHandle: {
    width: 56,
    height: 5,
    backgroundColor: colors.colorTextTertiary,
  },
  sheetContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  sheetScrollableContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  sheetTitle: {
    marginBottom: 16,
    paddingLeft: 6,
    paddingTop: 6,
    color: colors.colorTextPrimary,
    fontSize: 20,
    fontWeight: "800",
  },
  fixedSheetTitle: {
    marginHorizontal: 16,
  },
  sheetGroup: {
    marginBottom: 12,
  },
  sheetGroupTitle: {
    marginBottom: 8,
    paddingLeft: 6,
    color: colors.colorTextTertiary,
    fontSize: 13,
    fontWeight: "800",
  },
  sheetItem: {
    minHeight: 48,
    justifyContent: "center",
    borderRadius: 12,
    paddingHorizontal: 14,
    marginBottom: 6,
  },
  sheetItemActive: {
    backgroundColor: colors.colorBackgroundTertiary,
  },
  sheetItemDisabled: {
    opacity: 0.45,
  },
  sheetItemText: {
    color: colors.colorTextSecondary,
    fontSize: 16,
    fontWeight: "700",
  },
  sheetItemTextActive: {
    color: colors.colorTextPrimary,
  },
  sheetItemTextDisabled: {
    color: colors.colorTextDisabled,
  },
});
