import { Platform, StyleSheet } from "react-native";

import { colors } from "../../styles/colors";

export const SEEK_THUMB_WIDTH = 8;
export const SEEK_THUMB_HEIGHT = 20;
export const SEEK_THUMB_TOUCH_SIZE = 28;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? 28 : 0,
    backgroundColor: colors.appBackground,
  },
  tabView: {
    flex: 1,
  },
  tabBar: {
    marginHorizontal: 16,
    backgroundColor: "transparent",
    elevation: 0,
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 0,
  },
  tabIndicator: {
    height: 3,
    backgroundColor: colors.colorBorderInfo,
  },
  tabContent: {
    padding: 16,
    paddingBottom: 24,
    rowGap: 24,
  },
  loadingOptions: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  footer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    backgroundColor: colors.appBackground,
  },
  generateButton: {
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: colors.colorBackgroundInverse,
  },
  disabledButton: {
    opacity: 0.62,
  },
  generateText: {
    color: colors.colorTextInverse,
    fontSize: 18,
    fontWeight: "800",
  },
  inputGroup: {
    marginBottom: 0,
  },
  textAreaWrap: {
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: colors.colorBackgroundTertiary,
  },
  textArea: {
    flex: 1,
    minHeight: 70,
    color: colors.colorTextPrimary,
    fontSize: 15,
    lineHeight: 23,
  },
  countText: {
    alignSelf: "flex-end",
    marginTop: 8,
    color: colors.colorTextTertiary,
    fontSize: 12,
  },
  optionLabel: {
    color: colors.colorTextPrimary,
    fontSize: 14,
    fontWeight: "700",
    marginLeft: 1,
  },
  optionValue: {
    maxWidth: "58%",
    color: colors.colorTextTertiary,
    fontSize: 14,
    textAlign: "right",
  },
  optionBlock: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    padding: 16,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  optionBody: {
    marginTop: 12,
  },
  resolutionInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
  },
  resolutionInputBox: {
    flex: 1,
    height: 44,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.colorBorderSecondary,
    borderRadius: 10,
    paddingHorizontal: 12,
    backgroundColor: colors.colorBackgroundTertiary,
  },
  resolutionInlineLabel: {
    color: colors.colorTextTertiary,
    fontSize: 13,
    fontWeight: "700",
  },
  resolutionDivider: {
    width: 1,
    height: 20,
    marginHorizontal: 10,
    backgroundColor: colors.colorBorderTertiary,
  },
  resolutionInput: {
    flex: 1,
    height: "100%",
    minWidth: 48,
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: "transparent",
    color: colors.colorTextPrimary,
    fontWeight: "800",
    includeFontPadding: false,
    textAlign: "right",
    textAlignVertical: "center",
  },
  resolutionSwapButton: {
    width: 34,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  section: {
    marginBottom: 10,
  },
  sectionTitle: {
    paddingLeft: 2,
    marginBottom: 10,
    color: colors.colorTextPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  sectionContent: {
    marginBottom: 0,
  },
  selectOption: {
    marginBottom: 10,
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  selectValueWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    justifyContent: "flex-end",
    marginLeft: 16,
  },
  promptSwitchRow: {
    flexDirection: "row",
    alignSelf: "flex-start",
    alignItems: "center",
    gap: 8,
  },
  promptHeaderRow: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 8,
  },
  promptTextAreaWrap: {
    minHeight: 220,
  },
  addCharacterButton: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: colors.colorBorderTertiary,
    borderRadius: 14,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  addCharacterText: {
    color: colors.colorTextPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  characterPromptGroup: {
    // marginTop: 5,
    // backgroundColor: "red",
  },
  characterPromptGroupDisabled: {
    opacity: 0.48,
  },
  characterPromptTitle: {
    marginBottom: 8,
    paddingLeft: 2,
    color: colors.colorTextPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  characterPromptActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  characterPromptIconButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  characterPromptIconButtonActive: {
    backgroundColor: "#fff",
  },
  segmentButton: {
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: "transparent",
  },
  segmentButtonActive: {
    backgroundColor: "#fff",
  },
  segmentText: {
    color: colors.colorTextTertiary,
    fontWeight: "700",
  },
  segmentTextActive: {
    color: colors.appBackground,
  },
  seekOptionRow: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    // marginBottom: 14,
    marginLeft: 1,
  },
  seekOptionMain: {
    flex: 1,
  },
  stepperLabel: {
    marginBottom: 0,
    fontSize: 14,
    marginLeft: 0,
  },
  seekValueInput: {
    width: 72,
    height: 44,
    borderWidth: 1,
    borderColor: colors.colorBorderSecondary,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 0,
    backgroundColor: colors.colorBackgroundTertiary,
    color: colors.colorTextPrimary,
    fontSize: 15,
    fontWeight: "800",
    includeFontPadding: false,
    textAlign: "center",
    textAlignVertical: "center",
  },
  seekContainer: {
    marginTop: 0,
  },
  seekTrackWrap: {
    height: SEEK_THUMB_TOUCH_SIZE,
    justifyContent: "center",
  },
  seekTrack: {
    height: 12,
    overflow: "hidden",
    borderRadius: 6,
    backgroundColor: colors.colorBorderTertiary,
  },
  seekThumbTouch: {
    position: "absolute",
    top: 0,
    left: 0,
    width: SEEK_THUMB_TOUCH_SIZE,
    height: SEEK_THUMB_TOUCH_SIZE,
    alignItems: "center",
    justifyContent: "center",
  },
  seekThumb: {
    width: SEEK_THUMB_WIDTH,
    height: SEEK_THUMB_HEIGHT,
    borderRadius: 4,
    backgroundColor: colors.colorBackgroundInverse,
  },
  seedOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  seedRow: {
    width: 136,
    flexDirection: "row",
    gap: 10,
    marginLeft: 16,
  },
  seedInput: {
    flex: 1,
    height: 38,
    borderWidth: 1,
    borderColor: colors.colorBorderSecondary,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 0,
    backgroundColor: colors.colorBackgroundTertiary,
    color: colors.colorTextPrimary,
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  sheetContainer: {
    marginHorizontal: 14,
    zIndex: 20,
    elevation: 20,
  },
  sheetBackground: {
    borderRadius: 28,
    backgroundColor: colors.colorBackgroundSecondary,
  },
  sheetHandle: {
    width: 56,
    height: 5,
    backgroundColor: colors.colorTextTertiary,
  },
  sheetContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  sheetScrollableContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  sheetTitle: {
    marginBottom: 16,
    paddingLeft: 6,
    paddingTop: 6,
    color: colors.colorTextPrimary,
    fontSize: 20,
    fontWeight: "800",
  },
  fixedSheetTitle: {
    marginHorizontal: 16,
  },
  sheetGroup: {
    marginBottom: 12,
  },
  sheetGroupTitle: {
    marginBottom: 8,
    paddingLeft: 6,
    color: colors.colorTextTertiary,
    fontSize: 13,
    fontWeight: "800",
  },
  sheetItem: {
    minHeight: 48,
    justifyContent: "center",
    borderRadius: 12,
    paddingHorizontal: 14,
    marginBottom: 6,
  },
  sheetItemActive: {
    backgroundColor: colors.colorBackgroundTertiary,
  },
  sheetItemDisabled: {
    opacity: 0.45,
  },
  sheetItemText: {
    color: colors.colorTextSecondary,
    fontSize: 16,
    fontWeight: "700",
  },
  sheetItemTextActive: {
    color: colors.colorTextPrimary,
  },
  sheetItemTextDisabled: {
    color: colors.colorTextDisabled,
  },
});
